agents/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_agents, name='agents'),
    path('<int:pk>/', views.show_detail_agents, name='current_agent'),
    path('create/profile/', views.create_agent, name='create_profile'),
    path('create/user/', views.create_user, name='create_user'),
    path('create/org/', views.create_org, name='create_org'),
    path('create/address/', views.create_address, name='create_address'),
    path('<int:pk>/update/profile/', views.update_agent, name='update_profile'),
    path('<int:pk>/update/user/', views.update_user, name='update_user'),
    path('<int:pk>/update/org/', views.update_org, name='update_org'),
    path('<int:pk>/update/address/', views.update_address,
         name='update_address'),
    path('<int:pk>/delete/', views.delete_profile, name='delete_profile'),
]

crm_oil/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('agents/', include('agents.urls')),
    path('services/', include('services.urls')),
    path('apps/', include('applications.urls')),
    path('appeals/', include('appeal.urls')),
    path('contracts/', include('contracts.urls')),
    path('offers/', include('offers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models

PRIORITIES = (
    ('l', 'Низкий'),
    ('m', 'Средний'),
    ('h', 'Высокий'),
)


class Address(models.Model):
    state = models.CharField('Страна', max_length=64)
    city = models.CharField('Город', max_length=64)
    street = models.CharField('Улица', max_length=64)
    address = models.CharField('Строение', max_length=64, blank=True, default="")
    postcode = models.CharField('Почтовый индекс', max_length=32, blank=True, default="")

    def __str__(self):
        return self.get_complete_address()

    def get_complete_address(self):
        full_address = ""
        if self.state:
            full_address += self.state
        if self.city:
            if full_address:
                full_address += ", " + self.city
            else:
                full_address += self.city
        if self.street:
            if full_address:
                full_address += ", " + self.street
            else:
                full_address += self.street
        if self.address:
            if full_address:
                full_address += ", " + self.address
            else:
                full_address += self.address
        if self.postcode:
            if full_address:
                full_address += ", " + self.postcode
            else:
                full_address += self.postcode
        return full_address


class Org(models.Model):
    name = models.CharField('Название', max_length=64)
    web_site = models.CharField('Web-сайт', max_length=64, blank=True, default='')

    def __str__(self):
        return self.name


class User(models.Model):
    first_name = models.CharField('Имя', max_length=64)
    last_name = models.CharField('Фамилия', max_length=64)
    email = models.EmailField('Email', max_length=128, unique=True)
    phone = models.CharField('Номер телефона', max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET(''))
    org = models.ForeignKey(
        Org,
        null=True,
        on_delete=models.SET(None),
        blank=True,
        related_name="user_org",
    )
    address = models.ForeignKey(
        Address,
        related_name="adress_users",
        on_delete=models.SET(None),
        blank=True,
        null=True,
    )
    has_sales_access = models.BooleanField('Скидка', default=False)
    priority = models.CharField('Приоритет', max_length=3, choices=PRIORITIES, blank=True, default='')
    date_joined = models.DateTimeField('Дата создания', auto_now_add=True)
    description = models.TextField('Описание', blank=True, null=True)
    is_active = models.BooleanField('Активный', default=True)

    def __str__(self):
        return f'{self.user}, {self.org}'

agents/forms.py
from .models import Profile, Address, Org, User
from django import forms


class ProfileForm(forms.ModelForm):
    org = forms.ModelChoiceField(label="Организация",
                                 queryset=Org.objects.all())
    address = forms.ModelChoiceField(label="Адрес",
                                     queryset=Address.objects.all())
    user = forms.ModelChoiceField(label="Представитель организации",
                                  queryset=User.objects.all())

    class Meta:
        model = Profile
        fields = '__all__'


class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = '__all__'


class OrgForm(forms.ModelForm):

    class Meta:
        model = Org
        fields = '__all__'


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = '__all__'

agents/views.py
from django.shortcuts import render, redirect
from .models import Profile, Org
from .forms import ProfileForm, UserForm, AddressForm, OrgForm
from .filters import ProfileFilter
from django.contrib import messages


def show_agents(request):
    agents = Profile.objects.all()
    filter_agents = ProfileFilter(request.GET, queryset=agents)
    agents = filter_agents.qs
    return render(
        request, 'agents.html', {'agents': agents, 'filter': filter_agents})


def show_detail_agents(request, pk):
    current = Profile.objects.get(id=pk)
    return render(
        request, 'current_agent.html', {'current': current})


def create_agent(request):
    form = ProfileForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('agents')
    return render(request, 'create_agent.html', {'form': form})


def create_user(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('agents')
    return render(request, 'create_agent.html', {'form': form})


def create_org(request):
    form = OrgForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('agents')
    return render(request, 'create_agent.html', {'form': form})


def create_address(request):
    form = AddressForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('agents')
    return render(request, 'create_agent.html', {'form': form})


def update_address(request, pk):
    current = Profile.objects.get(id=pk)
    form = AddressForm(request.POST or None, instance=current.address)
    if form.is_valid():
        form.save()
        return redirect('current_agent', pk)
    return render(request, 'update_agent.html', {'form': form, 'pk': pk})


def update_agent(request, pk):
    current = Profile.objects.get(id=pk)
    form = ProfileForm(request.POST or None, instance=current)
    if form.is_valid():
        form.save()
        return redirect('current_agent', pk)
    return render(request, 'update_agent.html', {'form': form, 'pk': pk})


def update_user(request, pk):
    current = Profile.objects.get(id=pk)
    form = UserForm(request.POST or None, instance=current.user)
    if form.is_valid():
        form.save()
        return redirect('current_agent', pk)
    return render(request, 'update_agent.html', {'form': form, 'pk': pk})


def update_org(request, pk):
    current = Profile.objects.get(id=pk)
    form = OrgForm(request.POST or None, instance=current.org)
    if form.is_valid():
        form.save()
        return redirect('current_agent', pk)
    return render(request, 'update_agent.html', {'form': form, 'pk': pk})


def delete_profile(request, pk):
    current = Profile.objects.get(id=pk)
    try:
        current.delete()
    except Exception:
        messages.success(request, 'Невозможно удалить контрагента, так как существует обращение.')
        return redirect('current_agent', pk)
    return redirect('agents')

agents/templates/agents.html
{% extends 'main.html' %}

{% block content_body %}



<div class="col-md-8">
    <form method="get">
        {{ filter.form }}
        <div align="center">
            <button class="btn btn-primary" type="submit">Найти</button>
        </div>
    </form>
    {% if agents %}
    <div class="list-group">
        {% for agent in agents %}
        <a href="{% url 'current_agent' agent.id %}"
           class="list-group-item list-group-item-action"
           aria-current="true">
            <h4><strong>Организация</strong>: {{ agent.org.name }}</h4>
            <p class="mb-1"><strong>Представитель</strong>: {{ agent.user }}
            </p>
            <p class="mb-1"><strong>Email</strong>: {{ agent.user.email }}</p>
            <p class="mb-1"><strong>Адрес</strong>: {{ agent.address }}</p>
        </a>
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="col-md-4">
    <div class="btn-group-vertical">
        <a class="btn btn-secondary" role="button"
           href="{% url 'create_profile' %}">Добавить профиль контрагента</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'create_user' %}">Добавить представителя
            организации</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'create_org' %}">Добавить организацию</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'create_address' %}">Добавить адрес</a>
    </div>
</div>


{% endblock %}

agents/templates/create_agent.html
{% extends 'main.html' %}

{% block content_body %}
<div class="col-md-2">
    <a class="btn btn-dark" role="button"
           href="{% url 'agents' %}">Назад</a>
</div>
<div class="col-md-8 offset-md-2">
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <div align="center">
                <button class="btn btn-primary" type="submit">Создать</button>
            </div>
        </form>
</div>

{% endblock %}

agents/templates/current_agent.html
{% extends 'main.html' %}

{% block content_body %}

<div class="col-md-2">
    <a class="btn btn-dark" role="button"
       href="{% url 'agents' %}">Назад</a>
</div>
<div class="col-md-8">
    <div class="list-group">
        <div class="card">
            <div class="card-header">
                <h2>Профиль контрагента</h2>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Организация: {{ current.org.name }}
                </li>
                <li class="list-group-item">Веб-сайт организации:
                    {{ current.org.web_site }}
                </li>
                <li class="list-group-item">Адрес: {{ current.address }}</li>
                <li class="list-group-item">Приоритет:
                    {{ current.get_priority_display }}
                </li>
                <li class="list-group-item">Описание: {{ current.description }}
                </li>
                <li class="list-group-item">Дата создания:
                    {{ current.date_joined }}
                </li>
                {% if current.is_active%}
                <li class="list-group-item">Статус активности: Активен</li>
                {% else%}
                <li class="list-group-item">Статус активности: Неактивен</li>
                {% endif%}
                {% if current.has_sales_access %}
                <li class="list-group-item">Имеет скидку</li>
                {% endif%}
            </ul>
            <div class="card-header">
                <h2>Данные представителя организации</h2>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Имя: {{ current.user.first_name }}
                </li>
                <li class="list-group-item">Фамилия: {{ current.user.last_name }}
                </li>
                <li class="list-group-item">Email: {{ current.user.email }}
                </li>
                <li class="list-group-item">Телефон: {{ current.user.phone }}
                </li>
            </ul>
        </div>
    </div>
    <br>
    <div class="list-group">
        <div class="card">
            <div class="card-header">
                <h2>Предыдущие обращения</h2>
            </div>
            {% for appeal in current.appeal.all %}
            {% if appeal.status == 'n' %}
             <ul class="list-group list-group-flush">
                <a href="{% url 'appeal_current' appeal.id %}?id={{current.id}}"
                   class="list-group-item">{{ appeal }} </a>
             </ul>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <br>
    <div class="list-group">
        <div class="card">
            <div class="card-header">
                <h2>Активные заявки</h2>
            </div>
            {% for appeal in current.appeal.all %}
            {% for app in appeal.app.all %}
            {% if app.status != 'c' %}
             <ul class="list-group list-group-flush">
                <a href="{% url 'app_current' app.id %}?id={{current.id}}"
                   class="list-group-item">{{ app }} </a>
             </ul>
            {% endif %}
            {% endfor %}
            {% endfor %}
        </div>
    </div>
    <br>
    <div class="list-group">
        <div class="card">
            <div class="card-header">
                <h2>Коммерческие предложения</h2>
            </div>
            {% for contract in current.contract.all %}
            {% for offer in contract.offer.all %}
             <ul class="list-group list-group-flush">
                <a href="{% url 'offer_current' offer.id %}?id={{current.id}}"
                   class="list-group-item">{{ offer }} </a>
             </ul>
            {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-2">
    <div class="btn-group-vertical">
        <a class="btn btn-secondary" role="button"
           href="{% url 'update_profile' current.id %}">Обновить профиль
            контрагента</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'update_user' current.id %}">Обновить данные
            представителя организации</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'update_org' current.id %}">Обновить данные
            организации</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'update_address' current.id %}">Обновить данные
            адреса</a>
        <a class="btn btn-danger" role="button"
           href="{% url 'delete_profile' current.id %}">Удалить профиль
            контрагента</a>
    </div>
</div>

{% endblock %}

agents/templates/update_agent.html
{% extends 'main.html' %}

{% block content_body %}
<div class="col-md-2">
    <a class="btn btn-dark" role="button"
           href="{% url 'current_agent' pk %}">Назад</a>
</div>
<div class="col-md-8 offset-md-2">
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <div align="center">
                <button class="btn btn-primary" type="submit">Обновить</button>
            </div>
        </form>
</div>

{% endblock %}