agents/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_agents, name='agents'),
    path('<int:pk>/', views.show_detail_agents, name='current_agent'),
    path('create/profile/', views.create_agent, name='create_profile'),
    path('create/user/', views.create_user, name='create_user'),
    path('create/org/', views.create_org, name='create_org'),
    path('create/address/', views.create_address, name='create_address'),
    path('<int:pk>/update/profile/', views.update_agent, name='update_profile'),
    path('<int:pk>/update/user/', views.update_user, name='update_user'),
    path('<int:pk>/update/org/', views.update_org, name='update_org'),
    path('<int:pk>/update/address/', views.update_address,
         name='update_address'),
    path('<int:pk>/delete/', views.delete_profile, name='delete_profile'),
]

appeal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.appeal, name='appeal'),
    path('<int:pk>/', views.appeal_current, name='appeal_current'),
    path('create/', views.appeal_create, name='appeal_create'),
    path('<int:pk>/update/', views.appeal_update, name='appeal_update'),
    path('<int:pk>/delete/', views.delete_appeal, name='appeal_delete'),
]

crm_oil/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('agents/', include('agents.urls')),
    path('services/', include('services.urls')),
    path('apps/', include('applications.urls')),
    path('appeals/', include('appeal.urls')),
    path('contracts/', include('contracts.urls')),
    path('offers/', include('offers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appeal/models.py
from django.db import models
from django.contrib.auth.models import User
from contracts.models import Contract
from agents.models import Profile
from datetime import date
from django.utils import timezone

TIME_ZONE = timezone.get_default_timezone()

TOPICS = (
    (None, ''),
    ('cd', 'Заключение договора'),
    ('cs', 'Изменение параметра услуг'),
    ('ud', 'Корректировка договора'),
    ('dd', 'Расторжение договора'),
)
CHANNEL = (
    (None, ''),
    ('e', 'Email'),
    ('p', 'Телефон'),
    ('m', 'Мессенджер'),
)
STATUS = (
    ('r', 'Обработано'),
    ('n', 'Не обработано'),
)


class Appeal(models.Model):
    client = models.ForeignKey(
        Profile,
        on_delete=models.PROTECT,
        related_name='appeal',
    )
    name = models.CharField('Название', max_length=64, blank=True, default='')
    topic = models.CharField('Тема', max_length=3, choices=TOPICS)
    contract = models.ForeignKey(
        Contract,
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
    )
    created_on = models.DateTimeField('Дата создания', auto_now_add=True)
    closed_on = models.DateField('Срок обработки', blank=True, default=date.today)
    channel = models.CharField('Канал поступления', max_length=3, choices=CHANNEL)
    comment = models.TextField('Комментарий', blank=True, default='')
    status = models.CharField('Статус', max_length=3, choices=STATUS, default='n')

    class Meta:
        ordering = ['-created_on', ]

    def __str__(self):
        output = (
            f'{self.created_on.astimezone(TIME_ZONE).strftime("%d.%m.%Y %H:%M")},'
            f' {self.get_channel_display()}')

        return output

    def get_services(self):
        return self.contract.services

appeal/forms.py
from .models import Appeal
from agents.models import Profile
from contracts.models import Contract
from django import forms


class AppealForm(forms.ModelForm):
    client = forms.ModelChoiceField(
        queryset=Profile.objects.all(),
        label='Контрагент',
        empty_label='',
    )
    contract = forms.ModelChoiceField(
        queryset=Contract.objects.all(),
        label='Договор',
        empty_label='',
        required=False,
    )

    class Meta:
        model = Appeal
        exclude = ['created_by', 'status']

    def __init__(self, *args, **kwargs):
        super(AppealForm, self).__init__(*args, **kwargs)

        self.fields['client'].widget.attrs['class'] = 'form-select'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['topic'].widget.attrs['class'] = 'form-select'
        self.fields['channel'].widget.attrs['class'] = 'form-select'
        self.fields['contract'].widget.attrs['class'] = 'form-select'
        self.fields['closed_on'].widget.attrs['class'] = 'form-control'
        self.fields['comment'].widget.attrs['class'] = 'form-control'

appeal/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Appeal
from .forms import AppealForm


def appeal(request):
    appeals = Appeal.objects.all()
    return render(
        request, 'appeal.html', {'appeals': appeals})


def appeal_current(request, pk):
    agent_id = request.GET.get('id', '')
    current = Appeal.objects.get(id=pk)
    return render(
        request, 'current_appeal.html', {'current': current,
                                         'agent_id': agent_id})


def appeal_create(request):
    form = AppealForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.created_by = request.user
        instance.save()
        return redirect('appeal')
    return render(request, 'create_appeal.html', {'form': form})


def appeal_update(request, pk):
    current = Appeal.objects.get(id=pk)
    form = AppealForm(request.POST or None, instance=current)
    if form.is_valid():
        form.save()
        return redirect('appeal_current', pk)
    return render(request, 'update_appeal.html', {'form': form, 'pk': pk})


def delete_appeal(request, pk):
    current = Appeal.objects.get(id=pk)
    try:
        current.delete()
    except Exception:
        messages.success(request, 'Невозможно удалить обращение, так как существует заявка.')
        return redirect('appeal_current', pk)
    return redirect('appeal')

appeal/templates/appeal.html
{% extends 'main.html' %}

{% block content_body %}

{% if appeals %}

<div class="col-md-8">
    <div class="list-group">
        {% for appeal in appeals %}
        <a href="{% url 'appeal_current' appeal.id %}"
           class="list-group-item list-group-item-action"
           aria-current="true">
            <h4><strong>Обращение№{{ appeal.id }}</strong></h4>
            <p class="mb-1"><strong>Контрагент</strong>: {{ appeal.client }}</p>
            <p class="mb-1"><strong>Тема</strong>: {{ appeal.get_topic_display }}</p>
            <p class="mb-1"><strong>Дата создания</strong>: {{ appeal.created_on }}</p>
            <p class="mb-1"><strong>Статус</strong>: {{ appeal.get_status_display }}</p>
        </a>
        {% endfor %}
    </div>
</div>
{% endif %}
<div class="col-md-4">
    <div class="btn-group-vertical">
        <a class="btn btn-secondary" role="button"
           href="{% url 'appeal_create' %}">Создать обращение</a>
    </div>
</div>



{% endblock %}

appeal/templates/create_appeal.html
{% extends 'main.html' %}

{% block content_body %}
<div class="col-md-2">
    <a class="btn btn-dark" role="button"
           href="{% url 'appeal' %}">Назад</a>
</div>
<div class="col-md-8">
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <div align="center">
                <button class="btn btn-primary" type="submit">Создать</button>
            </div>
        </form>
</div>

{% endblock %}

appeal/templates/current_appeal.html
{% extends 'main.html' %}

{% block content_body %}

<div class="col-md-2">
    {% if agent_id %}
    <a class="btn btn-dark" role="button"
       href="{% url 'current_agent' agent_id %}">Назад</a>
    {% else %}
    <a class="btn btn-dark" role="button"
       href="{% url 'appeal' %}">Назад</a>
    {% endif %}
</div>
<div class="col-md-8">
    <div class="list-group">
        <div class="card">
            <div class="card-header">
                <h2>Обращение№{{ current.id }}</h2>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Контрагент: {{ current.client }}</li>
                <li class="list-group-item">Название: {{ current.name }}</li>
                <li class="list-group-item">Тема: {{ current.get_topic_display }}</li>
                <li class="list-group-item">Канал поступления: {{ current.get_channel_display }}</li>
                <li class="list-group-item">Договор: {{ current.contract|default:"" }}</li>
                <li class="list-group-item">Комментарий: {{ current.comment }}</li>
                <li class="list-group-item">Создан: {{ current.created_by }}</li>
                <li class="list-group-item">Дата создания: {{ current.created_on }}</li>
                <li class="list-group-item">Срок обработки: {{ current.closed_on }}</li>
                <li class="list-group-item">Статус: {{ current.get_status_display }}</li>
            </ul>
        </div>
    </div>
</div>
<div class="col-md-2">
    <div class="btn-group-vertical">
        <a class="btn btn-secondary" role="button"
           href="{% url 'app_create' %}?id={{current.id}} ">Создать заявку</a>
        <a class="btn btn-secondary" role="button"
           href="{% url 'appeal_update' current.id %}">Обновить обращение</a>
        <a class="btn btn-danger" role="button"
           href="{% url 'appeal_delete' current.id %}">Удалить обращение</a>
    </div>
</div>

{% endblock %}

appeal/templates/update_appeal.html
{% extends 'main.html' %}

{% block content_body %}
<div class="col-md-2">
    <a class="btn btn-dark" role="button"
           href="{% url 'appeal_current' pk %}">Назад</a>
</div>
<div class="col-md-8">
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <div align="center">
                <button class="btn btn-primary" type="submit">Обновить</button>
            </div>
        </form>
</div>

{% endblock %}